services:
  ai:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    restart: always
    networks:
      - realcoaching-network

  report:
    build:
      context: ./RealCoaching-report
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./RealCoaching-report:/app
      - /app/node_modules
    restart: always
    networks:
      - realcoaching-network

networks:
  realcoaching-network:
    driver: bridge
